### DISCUSSION TITLE
I can't understand why is using all this memory when idle

### DISCUSSION THREAD

**Discussion by Magneticdud** [borgmatic-collective/docker-borgmatic#231] [General]
```docker stats``` on my server, during a time when it is not doing a backup:

`borgmatic-data-1                    0.00%     786.3MiB / 62.19GiB   1.23%`

so i logged in the docker container to see what top is saying and, there's nothing to use that memory

```
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  598     0 root     S     3544   0%   2   0% bash
    1     0 root     S     1624   0%  10   0% {entry.sh} /bin/sh /entry.sh
  615   598 root     R     1620   0%   3   0% top
   13     1 root     S     1616   0%   2   0% /usr/sbin/crond -f -L /dev/stdout
```

my ```docker-compose.yml:```

```
version: '3'
services:
  data:
    image: b3vis/borgmatic:latest-msmtp
    volumes:
[...]
    networks:
      - mariadb
      - mongo
networks:
  mongo:
    external: true
  mariadb:
    external: true
```

What can i do to improve the situation, how to release the memory?
