### DISCUSSION TITLE
Image without cron

### DISCUSSION THREAD

**Discussion by fred-gb** [borgmatic-collective/docker-borgmatic#430] [Ideas]
Hi,

Is it possible to have docker-borgmatic without cron?

I would like to start docker compose with systemd timer and not have borgmatic always up.

Thanks

**Comment by witten** [comment]
Could you just `docker exec` borgmatic in the container from your systemd service?

**Reply by kimdre** [reply]
You can just overwrite the default command in your compose that the entrypoint executes.

For example

```yaml
services:
  backup:
    image: ghcr.io/borgmatic-collective/borgmatic:2.1.5@sha256:f6b0a640d72bf7bb628479246e7c919404917cc58ddc6cdfb8d2d40d786d3a26
    restart: "no"
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - |
        export BORG_PASSPHRASE="$$(cat /run/s6/container_environment/BORG_PASSPHRASE)" # Required to re-set variable because S6 unsets it during init
        export TZ=Europe/Berlin # Required to re-set variable because S6 unsets it during init
        borgmatic create
    environment:
      TZ: Europe/Berlin
      BACKUP_CRON: "0 0 31 2 *" # only for initialization, runs never because febuary never has 31 days
```
