### ISSUE TITLE
[1.7.11] Error "borg prune: error: argument -a/--glob-archives: There can be only one."

### ISSUE THREAD

**Issue by MegalodonBite** [borgmatic-collective/docker-borgmatic#225]
Hi,
first of all thank you very much for this project.

I'm about to use this docker image to run some backups.
I set up everything in a testing environment with version 1.7.9: `ghcr.io/borgmatic-collective/borgmatic:1.7.9`
This runs without an error for a few days now.

Then I just updated the docker image to 1.7.11 `ghcr.io/borgmatic-collective/borgmatic:1.7.11` and got a error.
Seems like it's an issue with `borgmatic` while creating the command and flags for `borg`:

Log
```
usage: borg prune [-h] [--critical] [--error] [--warning] [--info] [--debug]
                  [--debug-topic TOPIC] [-p] [--iec] [--log-json]
                  [--lock-wait SECONDS] [--bypass-lock] [--show-version]
                  [--show-rc] [--umask M] [--remote-path PATH]
                  [--remote-ratelimit RATE] [--upload-ratelimit RATE]
                  [--remote-buffer UPLOAD_BUFFER]
                  [--upload-buffer UPLOAD_BUFFER] [--consider-part-files]
                  [--debug-profile FILE] [--rsh RSH] [-n] [--force] [-s]
                  [--list] [--keep-within INTERVAL] [--keep-last SECONDLY]
                  [--keep-minutely MINUTELY] [-H HOURLY] [-d DAILY]
                  [-w WEEKLY] [-m MONTHLY] [-y YEARLY] [-P PREFIX | -a GLOB]
                  [--save-space] [-c SECONDS]
                  [REPOSITORY]
borg prune: error: argument -a/--glob-archives: There can be only one.
ssh://xxx@xxx.your-storagebox.de/./borg/testrepo: Error running actions for repository
Command 'borg prune --keep-hourly 2 --keep-daily 7 --keep-weekly 4 --keep-monthly 12 --keep-yearly 10 --glob-archives backup-* --glob-archives backup-* --stats --info ssh://xxx@xxx.your-storagebox.de/./borg/testrepo' returned non-zero exit status 2.
Error during prune/create/check.
```

You can see that the `--glob-archives` flag is added twice.

The `backup-` is added three times in the config.yaml for `storage`,`retention` and `consistency`

config.yaml
```
...

storage:
    encryption_passphrase: "xxx"
    compression: none
    ssh_command: 'ssh -p 23 -i /root/.ssh/id_rsa' # As BorgBackup is running on port 23 on the Storage Boxes, we have to overwrite the default ssh command in order to specify a port.
    archive_name_format: 'backup-{now}'

retention:
    keep_hourly: 2
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 12
    keep_yearly: 10
    prefix: 'backup-'

consistency:
    checks:
        - repository
        - archives
    prefix: 'backup-'
...
```

Hope this information helps!

For now I just switched back to 1.7.9 and everything runs smoothly.
