### ISSUE TITLE
Archives on listing don't survive to container re-creation

### ISSUE THREAD

**Issue by tmm360** [borgmatic-collective/docker-borgmatic#254]
I'm using Docker Swarm to maintain a borgmatic instance.
I'm still experimenting with it, but I'm having some issues understanding how cache is managed.

This is an extract of my docker swarm document:

```
version: "3"

services:
  
  admin_borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic
    environment:
      - BORG_PASSPHRASE=<change_me> # <-- change
      - TZ=Europe/Zurich
    volumes:
      - ./borgmatic/.ssh:/root/.ssh           # ssh key for remote repositories         ## <-- put ssh key
      - ./borgmatic/admin:/etc/borgmatic.d    # borgmatic config file(s)
      - admin_borg-cache:/root/.cache/borg    # checksums used for deduplication
      - admin_borg-config:/root/.config/borg  # borg config and keyfiles
      
      # backup sources
      - source-volume:/mnt/source-volume:ro                      # my source volume

volumes:
  admin_borg-cache:
  admin_borg-config:
  source-volume:
    external: true
```

my config.yaml file:

```
location:
  source_directories:
    - /mnt/source-volume

  repositories:
    - ssh://<myUserId>@<myUserId>.repo.borgbase.com/./repo

storage:
  compression: auto,zstd
  archive_name_format: '{hostname}-{now:%Y-%m-%d-%H%M%S}'
  retries: 5
  retry_wait: 5

retention:
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 12
  keep_yearly: 10

consistency:
  checks:
    - name: repository
      frequency: 4 weeks
    - name: archives
      frequency: 8 weeks
  check_last: 3

hooks:
  before_backup:
    - echo "Starting a backup job."
  after_backup:
    - echo "Backup created."
  on_error:
    - echo "Error while creating a backup."
```

Backup works without problems, I can list, extract, etc.  
Problems come when I decide to stop for test the container. Docker swarm creates another, but accessing into the new one if I execute `borgmatic list` I only receive an empty list of archives (even if the repository is recognized).

What is strange is that running `borg list ssh://<myUserId>@<myUserId>.repo.borgbase.com/./repo` I can see all of them, the olds and eventually also the new if created, but borgmatic is only able to list archives created with this same container. Am I missing something? How can I recreate locally the cache of borgmatic to recover also listing of missing archives?
