### ISSUE TITLE
Fuse module missing from the image

### ISSUE THREAD

**Issue by Belphemur** [borgmatic-collective/docker-borgmatic#270]
Hello,

When connecting to the image and starting bash. I then type:
```
borgmatic mount --archive latest --mount-point /mnt/mount
```

and it complains about lack of Fuse module:
```
ssh://rsync/./backup/unraid: Error running actions for repository
fuse: device not found, try 'modprobe fuse' first
Command 'borg mount --remote-path borg1 ssh://rsync/./backup/unraid::76a57cd7e1d3-2023-09-23T00:13:09.938386 /mnt/mount' returned non-zero exit status 2.

Need some help? https://torsion.org/borgmatic/#issues
```

Could the fuse module be added to the docker image so I can use it to mount archives ?

**Comment by Belphemur** [comment]
Actually fuse is properly setup. I had to change my docker compose to give access to fuse:

```yaml
  borgmatic:
      container_name: Borgmatic
      image: ghcr.io/borgmatic-collective/borgmatic
      restart: unless-stopped
      devices:
        - /dev/fuse
      cap_add:
        - SYS_ADMIN
```
