### ISSUE TITLE
Native Apprise Configuration: Send log outputs as part of the notification body does not work

### ISSUE THREAD

**Issue by beckenc** [borgmatic-collective/docker-borgmatic#286]
Hi all, 

I've tried to send borgmatic log outputs within the apprise email body, but it does not work somehow. I just get emails with a body with plain $(cat /tmp/backup_run.log) text in it (/tmp/backup_run.log does exist and is not empty). Looks like the shell command is not interpreted. Did I miss something?

I use the borgmatic docker image (`ghcr.io/borgmatic-collective/borgmatic`).
`borgmatic:/# borgmatic --version
1.8.5
`

My apprise configuration looks like this:
```
services:
    - url: *******
      label: mail

finish:
    title: ✅ SUCCESS
    body: $(cat /tmp/backup_run.log)

states:
    - finish
```
