### ISSUE TITLE
"The checks option now expects a list of key/value pairs" warning

### ISSUE THREAD

**Issue by televisi** [borgmatic-collective/docker-borgmatic#302]
I am currently using:

- borgmatic 1.8.8
- borg 1.2.7
- apprise 1.7.2

I've been using this config.yaml file for my backup, for some reason, post backup run, the following warning is displayed:

```
The checks option now expects a list of key/value pairs. 
Lists of strings for this option are deprecated and support will be removed from a future release.
```

The thing is, I'm not sure which config that I missed / will be deprecated, could someone please asisst?
Thanks

```
source_directories:
    - /mnt/backups

repositories:
    - path: ssh://user@ssh:23/./backups
      label: backups

ssh_command: ssh -i /root/.ssh/privateKey

compression: lzma,9
archive_name_format: 'backups-{now:%Y-%m-%d_T_%H:%M:%S}'

checks:
    - repository
    - archives

check_last: 3

skip_actions: 
    - compact
    - prune
    - check

before_backup:
    - echo "Starting backup"

after_backup:
    - echo "Finished backup"

on_error:
    - echo "Error during create/prune/compact/check"
    
apprise:
    services:
        - url: pover://abc@def
          label: borg
    start:
        title: Start Backup!
        body: Starting backup process
    finish:
        title: Success Backup!
        body: Finished backup process
    fail:
        title: Failed Backup!
        body: Failed backup process
    states:
        - start
        - finish
        - fail

healthchecks:
    ping_url: https://hc-ping.com/123456
```

**Comment by witten** [comment]
The warning is due to this part of the configuration:

```yaml
checks:
    - repository
    - archives
```

It should be changed as follows:

```yaml
checks:
    - name: repository
    - name: archives
```

See the documentation for more information: https://torsion.org/borgmatic/docs/how-to/deal-with-very-large-backups/#consistency-check-configuration

**Comment by televisi** [comment]
Thank you!
That was the bit that I was missing about!

Another question, on the [configuration reference guide ](https://torsion.org/borgmatic/docs/reference/configuration/), there is an additional frequency that I can add it:
```
# checks:
    # Name of consistency check to run: "repository",
    # "archives", "data", and/or "extract". "repository"
    # checks the consistency of the repository, "archives"
    # checks all of the archives, "data" verifies the
    # integrity of the data within the archives, and "extract"
    # does an extraction dry-run of the most recent archive.
    # Note that "data" implies "archives". See "skip_actions"
    # for disabling checks altogether.
    # - name: repository

      # How frequently to run this type of consistency check (as
      # a best effort). The value is a number followed by a unit
      # of time. E.g., "2 weeks" to run this consistency check
      # no more than every two weeks for a given repository or
      # "1 month" to run it no more than monthly. Defaults to
      # "always": running this check every time checks are run.
      # frequency: 2 weeks
```

Let's say I wanted to run the repository check every 6 months, and archives every 3 months, would the following configuration be the one I need?
```
checks:
    - name: repository, 6 months
    - name: archives, 3 months
```

Thanks

**Comment by witten** [comment]
Close! But try this instead:

```yaml
checks:
    - name: repository
      frequency: 6 months
    - name: archives
      frequency: 3 months
```

Also, in the future, you can file tickets about borgmatic directly here if they don't have anything to do with the Docker container: https://torsion.org/borgmatic/#issues
