### ISSUE TITLE
Docker environment variables are not passed to borgmatic

### ISSUE THREAD

**Issue by DamienVicet** [borgmatic-collective/docker-borgmatic#320]
Hello, I use borgmatic with docker-compose to backup my Nextcloud installation. You can find my setup repository here : https://gitlab.com/dvicet/nextcloud-collabora-docker-and-borg-backup-scripts

Here is how I launch borgmatic in my compose file :
```
services:
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic:1.8
    command: ["--verbosity", "1", "--list", "--stats"]
    container_name: borgmatic-nextcloud
    volumes:
      - nextcloud:/mnt/source/nextcloud:ro
      - data:/mnt/source/data:ro
      - ./borgmatic-config.yml:/etc/borgmatic.d/  # borgmatic config file(s)
      - ./ssh:/root/.ssh                          # ssh key for remote repositories
      - borgcache:/root/.cache/borg               # checksums used for deduplication
    environment:
      TZ: ${TIMEZONE}
      BORG_REPO: ${BORG_REPO}
      BORG_PASSPHRASE: ${BORG_PASSPHRASE}
      DB_PASSWORD: ${DB_PASSWORD}
```

Since borgmatic 1.8.10, firstly I need to change command to `["borgmatic", "--verbosity", "1", "--list", "--stats"]` to make borgmatic work. And then I got this error : 
```
borgmatic-nextcloud  | CRITICAL:None:Cannot find variable DB_PASSWORD in environment
```

It seems that my environment variable `DB_PASSWORD` it not passed to the container.

Is it a bug or am I missing something with my configuration ?

Thank you in advance !

**Comment by modem7** [comment]
Is there any particular reason you're using `command: ["--verbosity", "1", "--list", "--stats"]` instead of cron?

**Comment by mo-pyy** [comment]
I also noticed, that when setting the BORG_PASSPRASE variable, borg still asks me for my passphrase.  
I tried to use DEBUG_SECRETS, which did not change anything, so i rebuilt the image to always print the secrets and the passphrase I set using my environment showed up. It seems that the environment inside the container is completely broken.

image version is 1.8.10
using docker compose and example command from readme:
```bash
docker-compose run --rm borgmatic borgmatic list
```

**Comment by modem7** [comment]
> I also noticed, that when setting the BORG_PASSPRASE variable, borg still asks me for my passphrase. I tried to use DEBUG_SECRETS, which did not change anything, so i rebuilt the image to always print the secrets and the passphrase I set using my environment showed up. It seems that the environment inside the container is completely broken.
> 
> image version is 1.8.10 using docker compose from this repo and example command from readme:
> 
> ```shell
> docker-compose run --rm borgmatic borgmatic list
> ```

Could you paste your entire docker-compose.yaml here please (obviously make sure to change the password to something else). 

When I check the environment, it's certainly working.

```console
❯ docker exec -it Borgmatic /bin/bash
adb573f9a6be:/# echo $BORG_PASSPHRASE
594c03cb656e5202c96ae0b7eabad401ba32f94f595518084773dc7caecc6c82924d7e5fb6e7216a3e7304817468103c39c14d2fa7f776a679bf2f3918ce9f9a
adb573f9a6be:/#  
```

**Comment by DamienVicet** [comment]
I am not using cron inside the container but I launch the container with a script on the host machine like suggested in the readme : https://github.com/borgmatic-collective/docker-borgmatic?tab=readme-ov-file#run-borgmatic-like-a-binary-through-a-container 

I digged a bit more, it seems related to s6. I don't know exactly how it works but with env variable `S6_KEEP_ENV` I am able to use my env variables. But there is another problem : the exit code of borgmatic is not sent to the container so my script is not able to know if the backup failed or succeeded.

An alternative solution is to change the entrypoint of the container instead of using a command.

I finally changed my compose file to this :
```
services:
   # Backups with Borg
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic:1.8.11
    entrypoint: borgmatic --verbosity 1 --list --stats
    container_name: borgmatic-nextcloud
    volumes:
      - data:/mnt/source/data:ro
      - ./borgmatic-config.yml:/etc/borgmatic.d/  # borgmatic config file(s)
      - ./ssh:/root/.ssh                          # ssh key for remote repositories
      - borgcache:/root/.cache/borg               # checksums used for deduplication
    environment:
      TZ: ${TIMEZONE}
      BORG_REPO: ${BORG_REPO}
      BORG_PASSPHRASE: ${BORG_PASSPHRASE}
      DB_PASSWORD: ${DB_PASSWORD}
```
