### ISSUE TITLE
`BORG_PASSPHRASE_FILE` does not set `BORG_PASSPHRASE` environment variable

### ISSUE THREAD

**Issue by valfur03** [borgmatic-collective/docker-borgmatic#325]
I have the following borgmatic service in my _compose.yaml_ file:

```yaml
services:
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic:1.8.10
    environment:
      # BORG_PASSPHRASE: 'heremypassphrase'
      BORG_PASSPHRASE_FILE: /run/secrets/BORGMATIC_ENCRYPTION_PASSPHRASE
    volumes:
      - borg-config:/root/.config/borg
      - ./borgmatic/config:/etc/borgmatic.d:ro
      - /backup/borg/docker:/backup
    secrets:
      - BORGMATIC_ENCRYPTION_PASSPHRASE
    restart: unless-stopped
```

When using the `BORGMATIC_PASSPHRASE_FILE`, the `BORGMATIC_PASSPHRASE` is not set inside the container. Initializing repositories or creating archives also asks for my passphrase.

```
$ docker compose exec borgmatic borgmatic create --verbosity 1 --stats --list
local: Creating archive
Enter passphrase for key /backup/repo:
```

However, `BORGMATIC_PASSPHRASE` works as expected when passed as is to the container. It seems that the `_FILE` variable is not working in my case.

The logs still print this message when starting up:

```
Setting BORG_PASSPHRASE from the content of /run/secrets/BORGMATIC_ENCRYPTION_PASSPHRASE
Unsetting BORG_PASSPHRASE_FILE
```

---

**OS:** Fedora Linux version 38 (Server Edition)
**Docker version:** Docker version 25.0.2, build 29cf629
**Compose version:** Docker Compose version v2.24.5

---

This issue might be related to https://github.com/borgmatic-collective/docker-borgmatic/issues/320.
