### ISSUE TITLE
backup task fails: [Errno 18] Cross-device link

### ISSUE THREAD

**Issue by ultimateguy** [borgmatic-collective/docker-borgmatic#361]
My daily backups were running fine for months. Then this error cropped up a few days ago:

```
[Errno 18] Cross-device link: '/root/.borgmatic/checks' -> '/root/.local/state/borgmatic/checks'
/etc/borgmatic.d/config.yaml: An error occurred
```

This comes up when I use the command 'borgmatic' inside the container. I have no idea how to fix it. I have auto updates with watchtower enabled so maybe that caused it. ChatGPT suggests that it is an issue of hard linking between file systems and that my repository and cache volumes should be on the same file system, but none of its suggested solutions have worked.

My .env file:

```
TZ=[redacted]
BORG_PASSPHRASE=[redacted]
VOLUME_SOURCE=/home/hivemind
VOLUME_TARGET=/media/backupnas
VOLUME_ETC_BORGMATIC=./data/borgmatic.d
VOLUME_BORG_CONFIG=./data/.config/borg
#VOLUME_SSH=/home/Administrator/.ssh
VOLUME_BORG_CACHE=./data/.cache/borg
```

The `/media/backupnas` is a cifs mounted file system pointing to my Synology NAS.

Docker compose:

```
services:
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic
    container_name: borgmatic
    restart: unless-stopped
    volumes:
      - ${VOLUME_SOURCE}:/mnt/source/volume1:ro            # backup source
      - ${VOLUME_TARGET}:/mnt/borg-repository      # backup target
      - ${VOLUME_ETC_BORGMATIC}:/etc/borgmatic.d/  # borgmatic config file(s) + crontab.txt
      - ${VOLUME_BORG_CONFIG}:/root/.config/borg   # config and keyfiles
      #- ${VOLUME_SSH}:/root/.ssh                   # ssh key for remote repositories
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg     # checksums used for deduplication
    environment:
      - TZ=${TZ}
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
      - BACKUP_CRON=15 1 * * *
    dns:
      - 8.8.8.8
```
My config.yml:

```
source_directories:
    - /mnt/source/home/hivemind
    - /mnt/source/etc

repositories:
    - path: /mnt/borg-repository/hivemind_backup_repo
encryption_passphrase: "[redacted]"
keep_daily: 3
keep_monthly: 1
```
