### ISSUE TITLE
elif Block Not Entering as Expected When BACKUP_CRON Is Unset

### ISSUE THREAD

**Issue by LeoColman** [borgmatic-collective/docker-borgmatic#375]
https://github.com/borgmatic-collective/docker-borgmatic/blob/9a8c38ed4a60c4e3cbf38036e72b7cfa51bde00a/root/etc/s6-overlay/s6-rc.d/svc-cron/run#L43-L60

The current behavior of the script does not align with the intended functionality. Specifically, the `elif [[ -v BACKUP_CRON ]]` block is not entered when the `BACKUP_CRON` variable is unset.

The intended behavior is for the script to handle the case where `BACKUP_CRON` is not set and to enter the `elif` block with a default value.

----

**Steps to Reproduce**

1. Run the script with the `BACKUP_CRON` environment variable unset.
2. Observe that the `elif [[ -v BACKUP_CRON ]]` block is not executed, and the script proceeds to the else block instead.

----

**Expected Behavior**

When the `BACKUP_CRON` variable is unset, the script should enter the `elif` block and set `BACKUP_CRON` to the default value (`0 1 * * *`) and apply the corresponding cron job.

----

**Actual Behavior**

When `BACKUP_CRON` is unset, the script skips the `elif` block and falls into the `else` block, applying the default `crontab.txt` instead.

----
**Proposed Fix**

Update the condition for the `elif` block to explicitly handle the unset `BACKUP_CRON` variable. Suggested change:

```
elif [[ -z "${BACKUP_CRON+x}" ]]; then
    BACKUP_CRON="${BACKUP_CRON:-"0 1 * * *"}"
    CRON_COMMAND="${CRON_COMMAND:-"/usr/local/bin/borgmatic --stats -v 0 2>&1"}"
    echo "$BACKUP_CRON $CRON_COMMAND" > /etc/crontabs/root
    echo "Applying custom cron"
```

The `[[ -z "${BACKUP_CRON+x}" ]]` check ensures that the block is entered when `BACKUP_CRON` is not set.

----

**Current Workaround**

The current workaround that I found was to set the default value in the config too:

```
  backup:
    image: b3vis/borgmatic
    volumes:
      - database:/data/database
      - redmine:/data/redmine
      - ssh:/root/.ssh/
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed
    configs:
      - source: borgmatic-config-redmine
        target: /etc/borgmatic.d/config.yaml
```
