### ISSUE TITLE
Unable to access mounted dir from the host

### ISSUE THREAD

**Issue by koichirose** [borgmatic-collective/docker-borgmatic#380]
Following the readme [here](https://github.com/borgmatic-collective/docker-borgmatic?tab=readme-ov-file#restoring-backups), I created this `docker-compose.restore.yml` file:
```
services:
  borgmatic:
    container_name: borg-restore
    cap_add:
      - SYS_ADMIN
    volumes:
      - /tmp/borg:/restore
    security_opt:
      - apparmor:unconfined
      - label:disable
    devices:
      - /dev/fuse:/dev/fuse
    command: /bin/sh
```
    
Then I run:
`docker compose -f $HOME/docker/borgmatic/docker-compose.yml -f $HOME/docker/borgmatic/docker-compose.restore.yml run --rm borgmatic`

And I run this inside the container:
`borg mount --remote-path=borg1 user@host.rsync.net:myrepo /restore` (repo is at rsync.net)

I can browse `/restore` from within the container, but `/tmp/borg` on the host contains 0 files. I also tried different dirs in my host.
What am I missing?
