### ISSUE TITLE
Regression: "mariadb-dump: "TLS/SSL error: SSL is required, but the server does not support it" when trying to connect" after update to 1.9.5

### ISSUE THREAD

**Issue by PyroDevil** [borgmatic-collective/docker-borgmatic#382]
I am using the borgmatic container to backup a mailcow setup, and the update from 1.9.4 to 1.9.5 broke backup of the mariadb database.

It works fine with the 1.9.4 version of the borgmatic docker container, but the identical configuration fails with 1.9.5 with this error:

```
mariadb-dump: Got error: 2026: "TLS/SSL error: SSL is required, but the server does not support it" when trying to connect
storagebox: Error running actions for repository
Command 'mariadb-dump --default-character-set=utf8mb4 --add-drop-database --user mailcow --databases mailcow --result-file /tmp/borgmatic-e7_6n_70/./borgmatic/mariadb_databases/localhost/mailcow' returned non-zero exit status 2.
```

MariaDB parts of the borgmatic configuration:

```
mariadb_databases:
    - name: ${DBNAME}
      username: ${DBUSER}
      password: ${DBPASS}
      options: --default-character-set=utf8mb4
```

Only the update of the container image to 1.9.5 triggers this, all other containers and configuration stay the same. And I could not find any documentation about what configuration option has changed.
