### ISSUE TITLE
Apprise sometimes fails with error 400

### ISSUE THREAD

**Issue by Nyarumi** [borgmatic-collective/docker-borgmatic#387]
Basically what the title says. For some reason, Apprise can’t send the notification when borgmatic successfully finishes, but it has no problem sending the starting notification.

I get this in my logs:
```
Failed to send to Discord notification: Bad Request - Unsupported Parameters., error=400.
/etc/borgmatic.d/config.yaml: Error sending some Apprise notifications 
```

And my config.yaml looks like this:

```
apprise:
    states:
        - start
        - finish
        - fail

    services:
        - url: discord://123456789/aAbBcC1234>
          label: discord

    start:
        title: Starting backup!
        body: Started!

    finish:
        title: Backed up successfully!
        body: Success!

    fail:
        title: Could not complete the backup!
        body: Failure!
```

As far as I can tell, none of the notifications differ in the syntax. I tried changing them to be the exact same text and I got the same error. Maybe the log that is attached to the notification isn’t being sanitized correctly?
